codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: '60...100'

  status:
    project:
      default:
        target: 60%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 50%
        threshold: 10%
        informational: false

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - 'tests/**/*'
  - '**/__pycache__'
  - '**/*.pyc'
  - 'node_modules/**/*'
  - 'htmlcov/**/*'
  - '.pytest_cache/**/*'
