security:
  risk_level: Low
  requirements:
    sandboxing_required: false
    human_in_loop_required: false
    audit_logging: false
    data_access_scope:
    - internal
    risk_factors: []
categorization:
  job_function: sales
  jtbd:
    job: This guide provides opinionated, actionable best practices for structuring,
      optimizing, and securing GitLab CI/CD pipelines, focusing on modern patterns
      and avoiding common pitfalls.
    context: When working in cursor_rules domain
    outcome: Successfully execute gitlab-ci
composability:
  hints:
  - 'can_chain_to: success'
  - 'can_chain_to: failure'
